# Generated by Django 4.0 on 2022-03-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_of_the_following', to='network.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_of_the_followers', to='network.user'),
        ),
    ]
